on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: gb
      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          repository: ethanriverpage/GB-Project-WebEmu
          path: main
      - name: Build Game Boy ROM
        uses: wujood/gbdk-2020-github-builder@1.0.7
        with:
          subdirectory: ./gb
          output-name: rom
          source: main.c
      #- name: Create release
      #  uses: marvinpinto/action-automatic-releases@latest
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #    automatic_release_tag: "latest-dev"
      #    title: Development Release
      #    prerelease: true
      #    files: gb/obj/GB-Project-DevOps.gb
      - name: Add ROM to zip
        run: |
          cd ./gb/obj && mv GB-Project-DevOps.gb rom.gb && zip ../../s3.zip rom.gb

      - name: Add web code to zip
        run: |
          cd ./main/app && zip -g ../../s3.zip -r .
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: s3
          path: s3.zip
  aws:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Download s3.zip
        uses: actions/download-artifact@v2
        with:
          name: s3
      #- name: Unzip files
      #  run: |
      #    mkdir s3 && unzip s3.zip -d ./s3
      - name: Upload to s3
        run: aws s3 cp ./s3.zip s3://gb.ethanriver.page/s3.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
