name: Build Game Boy ROM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Game Boy ROM
        run: |
          make
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: Release "${{ github.ref }}"
          prerelease: true
          files: obj/GB-Project-DevOps.gb
