name: Build Game Boy ROM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Game Boy ROM
        run: |
          make
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release "${{ github.ref }}"
          draft: false
          prerelease: false
          assets: obj/GB-Project-DevOps.gb
