on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: gb
      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          repository: ethanriverpage/GB-Project-WebEmu
          path: main
      - name: Build Game Boy ROM
        run: |
          cd ./gb && make
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-dev"
          title: Development Release
          prerelease: true
          files: gb/obj/GB-Project-DevOps.gb
