on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: gb
      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          repository: ethanriverpage/GB-Project-WebEmu
          path: main
      - name: Build Game Boy ROM
        run: |
          cd ./gb && make
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #automatic_release_tag: "latest-dev"
          title: Development Release
          prerelease: true
          files: gb/obj/GB-Project-DevOps.gb
      - name: Add ROM to zip
        run: |
          zip ../s3.zip -i ./gb/obj/GB-Project-DevOps.gb
      - name: Add web code to zip
        run: |
          cd ../ && zip -g ../s3.zip -r .
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: s3
          path: s3.zip
